[build]
  command = "yarn install && yarn build"
  publish = ".next"
  
[build.environment]
  # cache Cypress binary in local "node_modules" folder
  # so Netlify caches it
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  # set TERM variable for terminal output
  TERM = "xterm"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[plugins]]
# runs Cypress tests against the deployed URL
package = "netlify-plugin-cypress"
  [plugins.inputs]
    # run E2E tests against the deployed URL
    group = 'deployed'
    enable = true
    record = true
  [plugins.inputs.postBuild]
    # run E2E tests against locally built site
    # before deploying it
    enable = true
    group = 'build'
    