name: e2e
on:
  workflow_dispatch:
    inputs:
      deployPrimeUrl:
        description: Deployed URL
        required: true
jobs:
  e2e:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Current Git info $GITHUB_WORKFLOW $GITHUB_REF $GITHUB_SHA"
      - run: echo "Testing url-> ${{ github.event.inputs.deployPrimeUrl }}"

      - name: Checkout
        uses: actions/checkout@v2

      # test the deployed site using
      # https://github.com/cypress-io/github-action
      - name: Cypress run 🏃‍♀️
        uses: cypress-io/github-action@v2
        with:
          install: true
          browser: chrome
          headless: true
          record: true
          command: npx cypress run --browser chrome --headless --config baseUrl=${{ github.event.inputs.deployPrimeUrl }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
