name: e2e
on:
  workflow_call:
    inputs:
      deployPrimeUrl:
        required: true
        type: string
jobs:
  e2e:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # test the deployed site using
      # https://github.com/cypress-io/github-action
      - name: Cypress run 🏃‍♀️
        uses: cypress-io/github-action@v2
        with:
          install: true
          browser: chrome
          headless: true
          record: true
          command: npx cypress run --browser chrome --headless --config baseUrl=${{ inputs.deployPrimeUrl }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
