name: e2e
on:
  workflow_dispatch:
    inputs:
      # siteName:
      #   description: Site Name
      #   required: false
      deployPrimeUrl:
        description: Deployed URL
        required: true
      # commit:
      #   description: Original repo commit SHA
      #   required: false
jobs:
  show-event:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Current Git info $GITHUB_WORKFLOW $GITHUB_REF $GITHUB_SHA"
      - run: echo "Testing url ${{ github.event.inputs.deployPrimeUrl }}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn

      # test the deployed site using
      # https://github.com/cypress-io/github-action
      - name: Cypress run 🏃‍♀️
        uses: cypress-io/github-action@v2
        with:
          install: false
          browser: chrome
          headless: true
          record: true
          config: baseUrl=${{ github.event.inputs.deployPrimeUrl }}
          command: yarn cypress:headless
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
