name: Build and Deploy to Netlify
on:
  # push:
  pull_request:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Cache node modules and next folder
      - name: 📬 Caching
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ${{ github.workspace }}/.next/cache
            ${{ github.workspace }}/.netlify
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn-lock.json') }}

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: 🧰 Install dependencies
        run: yarn

      - name: 📦 Build project
        env:
          CMS_API_ENDPOINT: ${{ secrets.CMS_API_ENDPOINT }}
          CMS_API_USERNAME: ${{ secrets.CMS_API_USERNAME }}
          CMS_API_PASSWORD: ${{ secrets.CMS_API_PASSWORD }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          NEXT_PUBLIC_ANALYTICS_ID: ${{ secrets.NEXT_PUBLIC_ANALYTICS_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: yarn netlify

      # - name: 🧹 Run lint
      #   run: npm run lint

      # - name: 🐛 Run tests
      #   run: npm run test

      # Deploy to Netlify with a personalized message
      - name: 🚀 Deploy to Netlify
        # id: deploy-netlify
        # uses: netlify/actions/cli@master
        env:
          CMS_API_ENDPOINT: ${{ secrets.CMS_API_ENDPOINT }}
          CMS_API_USERNAME: ${{ secrets.CMS_API_USERNAME }}
          CMS_API_PASSWORD: ${{ secrets.CMS_API_PASSWORD }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          NEXT_PUBLIC_ANALYTICS_ID: ${{ secrets.NEXT_PUBLIC_ANALYTICS_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: npx netlify deploy -m 'v${{ steps.package-version.outputs.current-version}} ・ ${{ github.head_ref }}'

      # - name: Set env variables
      #   run: |
      #     export CMS_API_ENDPOINT=${{ secrets.CMS_API_ENDPOINT }}
      #     export CMS_API_USERNAME=${{ secrets.CMS_API_USERNAME }}
      #     export CMS_API_PASSWORD=${{ secrets.CMS_API_PASSWORD }}
      #     export SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
      #     export NEXT_PUBLIC_ANALYTICS_ID=${{ secrets.NEXT_PUBLIC_ANALYTICS_ID }}
      # - name: Build Nextjs Site
      #   run: |
      #     export CMS_API_ENDPOINT=${{ secrets.CMS_API_ENDPOINT }}
      #     export CMS_API_USERNAME=${{ secrets.CMS_API_USERNAME }}
      #     export CMS_API_PASSWORD=${{ secrets.CMS_API_PASSWORD }}
      #     export SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
      #     export NEXT_PUBLIC_ANALYTICS_ID=${{ secrets.NEXT_PUBLIC_ANALYTICS_ID }}
      #     yarn build
      #     cp -r .next build
      #     ls build
      # - name: Deploy
      #   uses: jsmrcaga/action-netlify-deploy@master
      #   # run: |
      #   #   export CMS_API_ENDPOINT=${{ secrets.CMS_API_ENDPOINT }}
      #   #   export CMS_API_USERNAME=${{ secrets.CMS_API_USERNAME }}
      #   #   export CMS_API_PASSWORD=${{ secrets.CMS_API_PASSWORD }}
      #   #   export SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
      #   #   export NEXT_PUBLIC_ANALYTICS_ID=${{ secrets.NEXT_PUBLIC_ANALYTICS_ID }}
      #   with:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #     deploy_alias: ${{ env.BRANCH_NAME }}
      #     build_directory: ".next"
      #   env:
      #     CMS_API_ENDPOINT: ${{ secrets.CMS_API_ENDPOINT }}
      #     CMS_API_USERNAME: ${{ secrets.CMS_API_USERNAME }}
      #     CMS_API_PASSWORD: ${{ secrets.CMS_API_PASSWORD }}
      #     SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      #     NEXT_PUBLIC_ANALYTICS_ID: ${{ secrets.NEXT_PUBLIC_ANALYTICS_ID }}
      # # Creates a status check with link to preview
      # - name: Status check
      #   uses: Sibz/github-status-action@v1.1.1
      #   with:
      #     authToken: ${{ secrets.GITHUB_TOKEN }}
      #     context: Netlify preview
      #     state: success
      #     target_url: https://${{ env.BRANCH_NAME }}.netlify.app
      # env:
      #   CMS_API_ENDPOINT: ${{ secrets.CMS_API_ENDPOINT }}
      #   CMS_API_USERNAME: ${{ secrets.CMS_API_USERNAME }}
      #   CMS_API_PASSWORD: ${{ secrets.CMS_API_PASSWORD }}
      #   SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      #   NEXT_PUBLIC_ANALYTICS_ID: ${{ secrets.NEXT_PUBLIC_ANALYTICS_ID }}
