name: Unit and DOM testing

on:
  # push:
  #   branches: [$default-branch]
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: Borales/actions-yarn@v3.0.0
        with:
          cmd: install
        env:
          CI_TEST: true
      - uses: Borales/actions-yarn@v3.0.0
        with:
          cmd: test
